apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-web-content
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/static-website"
