apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-static
  template:
    metadata:
      labels:
        app: web-static
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts:
            - name: web-content
              mountPath: /usr/share/nginx/html
      volumes:
        - name: web-content
          persistentVolumeClaim:
            claimName: pvc-web-content
